import React from 'react'


    const cities = [
      "Amsterdam",
      "Athens",
      "Auckland",
      "Bangkok",
      "Barcelona",
      "Beijing",
      "Belfast",
      "Berlin",
      "Birmingham",
      "Bordeaux",
      "Boston",
      "Brisbane",
      "Brussels",
      "Budapest",
      "Buenos Aires",
      "Cairo",
      "Cape Town",
      "Chicago",
      "Chongqing",
      "Copenhagen",
      "Dallas",
      "Delhi",
      "Denver",
      "Dubai",
      "Dublin",
      "Edinburgh",
      "Florence",
      "Frankfurt",
      "Glasgow",
      "Hamburg",
      "Helsinki",
      "Ho Chi Minh City",
      "Hokkaido",
      "Hong Kong",
      "Honolulu",
      "Houston",
      "Istanbul",
      "Jakarta",
      "Johannesburg",
      "Kansas City",
      "Kuala Lumpur",
      "Kyoto",
      "Las Vegas",
      "Leeds",
      "Lisbon",
      "Liverpool",
      "London",
      "Los Angeles",
      "Lyon",
      "Macau",
      "Madrid",
      "Manchester",
      "Manila",
      "Melbourne",
      "Mexico City",
      "Miami",
      "Milan",
      "Montreal",
      "Moscow",
      "Mumbai",
      "Munich",
      "Nairobi",
      "Nashville",
      "New Orleans",
      "New York City",
      "Nice",
      "Okinawa",
      "Orlando",
      "Osaka",
      "Oslo",
      "Ottawa",
      "Paris",
      "Perth",
      "Philadelphia",
      "Phuket",
      "Pittsburgh",
      "Portland",
      "Prague",
      "Quebec City",
      "Raleigh",
      "Reykjavik",
      "Riga",
      "Rio de Janeiro",
      "Rome",
      "Saint Petersburg",
      "San Diego",
      "San Francisco",
      "San Jose",
      "Santiago",
      "São Paulo",
      "Seattle",
      "Seoul",
      "Shanghai",
      "Singapore",
      "Stockholm",
      "Sydney",
      "Taipei",
      "Tallinn",
      "Tampa",
      "Tbilisi",
      "Tel Aviv",
      "Tokyo",
      "Toronto",
      "Valencia",
      "Vancouver",
      "Vienna",
      "Warsaw",
      "Washington D.C.",
      "Wellington",
      "Zurich",
    ];





export default cities